       IDENTIFICATION DIVISION.
       PROGRAM-ID. LEARN-FILE.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.

       DATA DIVISION.
       
       FILE SECTION.

       WORKING-STORAGE SECTION.
       
       LOCAL-STORAGE SECTION.
       
       PROCEDURE DIVISION.
           DISPLAY "Hello !"
       STOP RUN.
